// GERADO por scripts/generate-icons.mjs — não edite à mão.
import type * as React from 'react';
import type { IconName } from '../names';
import * as Svgs from './svg';

/**
 * Registro nome → componente SVG (gerados do Figma via svgr, em `./svg`).
 * Cada ícone carrega a própria cor do Figma; o `Icon` só controla o tamanho.
 */
export const registry: Record<IconName, (props: React.SVGProps<SVGSVGElement>) => React.JSX.Element> = {
  'account-about-zupper': Svgs.AccountAboutZupper,
  'account-address': Svgs.AccountAddress,
  'account-block': Svgs.AccountBlock,
  'account-blocked': Svgs.AccountBlocked,
  'account-help': Svgs.AccountHelp,
  'account-liked': Svgs.AccountLiked,
  'account-login': Svgs.AccountLogin,
  'account-password': Svgs.AccountPassword,
  'account-personal-data': Svgs.AccountPersonalData,
  'account-posts': Svgs.AccountPosts,
  'account-preferences': Svgs.AccountPreferences,
  'account-privacy': Svgs.AccountPrivacy,
  'account-terms': Svgs.AccountTerms,
  'account-unblock': Svgs.AccountUnblock,
  'add-day': Svgs.AddDay,
  'apple-logo': Svgs.AppleLogo,
  'back-arrow': Svgs.BackArrow,
  calendar: Svgs.Calendar,
  'calendar-03': Svgs.Calendar03,
  'chevron-right': Svgs.ChevronRight,
  'chevron-right-dark': Svgs.ChevronRightDark,
  clock: Svgs.Clock,
  close: Svgs.Close,
  'close-circle': Svgs.CloseCircle,
  'comment-send': Svgs.CommentSend,
  community: Svgs.Community,
  'content-dica': Svgs.ContentDica,
  'content-dica-white': Svgs.ContentDicaWhite,
  'content-foto': Svgs.ContentFoto,
  'content-foto-white': Svgs.ContentFotoWhite,
  'content-roteiro': Svgs.ContentRoteiro,
  'content-roteiro-white': Svgs.ContentRoteiroWhite,
  'dot-separator': Svgs.DotSeparator,
  'dropdown-arrow': Svgs.DropdownArrow,
  edit: Svgs.Edit,
  email: Svgs.Email,
  'email-sent': Svgs.EmailSent,
  eye: Svgs.Eye,
  'eye-slash': Svgs.EyeSlash,
  'facebook-logo': Svgs.FacebookLogo,
  fire: Svgs.Fire,
  'fire-destinos': Svgs.FireDestinos,
  globe: Svgs.Globe,
  'google-logo': Svgs.GoogleLogo,
  heart: Svgs.Heart,
  location: Svgs.Location,
  lock: Svgs.Lock,
  'media-camera': Svgs.MediaCamera,
  'media-gallery': Svgs.MediaGallery,
  'nav-conta': Svgs.NavConta,
  'nav-conta-active': Svgs.NavContaActive,
  'nav-inicio': Svgs.NavInicio,
  'nav-inicio-neutral': Svgs.NavInicioNeutral,
  'nav-pedidos': Svgs.NavPedidos,
  'nav-reservar': Svgs.NavReservar,
  'oferta-hospedagens': Svgs.OfertaHospedagens,
  'oferta-pacotes': Svgs.OfertaPacotes,
  'oferta-passagens': Svgs.OfertaPassagens,
  'password-reset-success': Svgs.PasswordResetSuccess,
  publish: Svgs.Publish,
  'quick-hospedagens': Svgs.QuickHospedagens,
  'quick-pacotes': Svgs.QuickPacotes,
  'quick-voos': Svgs.QuickVoos,
  'roteiro-card-edit': Svgs.RoteiroCardEdit,
  search: Svgs.Search,
  'social-comment': Svgs.SocialComment,
  'social-more': Svgs.SocialMore,
  'social-share': Svgs.SocialShare,
  'status-removed': Svgs.StatusRemoved,
  'status-review': Svgs.StatusReview,
  'status-success': Svgs.StatusSuccess,
  'success-check': Svgs.SuccessCheck,
  'tab-dicas-active': Svgs.TabDicasActive,
  'tab-dicas-inactive': Svgs.TabDicasInactive,
  'tab-fotos-active': Svgs.TabFotosActive,
  'tab-fotos-inactive': Svgs.TabFotosInactive,
  'tab-roteiros-active': Svgs.TabRoteirosActive,
  'tab-roteiros-inactive': Svgs.TabRoteirosInactive,
  trash: Svgs.Trash,
  user: Svgs.User,
  'user-circle': Svgs.UserCircle,
  verified: Svgs.Verified,
  'warning-triangle': Svgs.WarningTriangle,
};
